source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'opal', github: 'janbiedermann/opal', branch: 'raise_platform_foundation'
gem 'opal-up', path: '../'
